import streamlit as st
import requests
import io
from PIL import Image
from deep_translator import GoogleTranslator

# --- 設定 ---
# StreamlitのSecretsからトークンを取得
HF_TOKEN = st.secrets["HF_TOKEN"]

# 最新のSD3.5 Large用URL（router経由）
API_URL = "https://router.huggingface.co/hf-inference/models/stabilityai/stable-diffusion-3.5-large-turbo"
headers = {"Authorization": f"Bearer {HF_TOKEN}"}

# 1. アプリの見た目設定
st.set_page_config(page_title="SD3.5 Image Generator", layout="centered")
st.subheader("🚀 Stable Diffusion 3.5 Large")
st.write("プロンプトを日本語で入力すると、AIが画像を生成します。")

# 2. 入力エリア
prompt_base = st.text_area("① ベース設定 (例: 実写風、アニメ風):", 
                          value="photorealistic, highly detailed, 8k",
                          placeholder="どんな雰囲気にするか入力")

prompt_add = st.text_area("② 追加指示 (例: 宇宙を泳ぐクジラ):", 
                         placeholder="具体的に何を描くか入力")

negative_ja = st.text_area("NGプロンプト (入れたくないもの):", 
                          value="文字、ロゴ、低画質、奇妙な手",
                          placeholder="日本語で入力")

# 3. 翻訳とデータ準備
combined_en = ""
negative_en = ""

if prompt_base or prompt_add:
    # 日本語を合体させて英語に翻訳
    full_prompt_ja = f"{prompt_base}、{prompt_add}"
    combined_en = GoogleTranslator(source='ja', target='en').translate(full_prompt_ja)
    
    # NGプロンプトも翻訳
    if negative_ja:
        negative_en = GoogleTranslator(source='ja', target='en').translate(negative_ja)

# 4. 生成ボタン
if st.button("✨ 画像を生成する"):
    if not (prompt_base or prompt_add):
        st.error("プロンプトを何か入力してください")
    else:
        with st.spinner("SD3.5が考え中... (初回は1〜2分かかる場合があります)"):
            # SD3.5が受け付ける形式にデータを整える
            payload = {
                "inputs": combined_en,
                "parameters": {
                    "negative_prompt": negative_en,
                    "num_inference_steps": 40, # 描き込みの細かさ
                    "guidance_scale": 4.5      # 指示にどれだけ忠実に従うか
                }
            }
            
            # AIにリクエストを送信
            response = requests.post(API_URL, headers=headers, json=payload)
            
            if response.status_code == 200:
                # 成功したら画像を表示
                image_bytes = response.content
                image = Image.open(io.BytesIO(image_bytes))
                st.image(image, caption="Generated by SD3.5", use_container_width=True)
            elif response.status_code == 503:
                # サーバーが準備中の場合
                st.info("モデルを起動中です。1分ほど待ってからもう一度押してください。")
            elif response.status_code == 401:
                st.error("トークンが正しくありません。Secretsの設定を確認してください。")
            else:
                # その他のエラー（400や410など）
                st.error(f"エラーが発生しました。 (Status Code: {response.status_code})")
                st.write("理由:", response.text)
