import streamlit as st
import requests
import io
from PIL import Image
from deep_translator import GoogleTranslator

# --- 設定 ---
HF_TOKEN = st.secrets["HF_TOKEN"]

# ご指定いただいた最新のAPI URL
API_URL = "https://router.huggingface.co/hf-inference/models/stabilityai/stable-diffusion-xl-base-1.0"
headers = {"Authorization": f"Bearer {HF_TOKEN}"}

# 1. アプリの見た目設定
st.set_page_config(page_title="SD3.5 Large App", layout="centered")
st.subheader("🚀 Stable Diffusion 3.5 Large")

# 2. 入力エリア（デフォルト文字なし・スッキリ版）
prompt_base = st.text_area("① ベース設定 (雰囲気など):", value="", placeholder="例: masterpiece, high quality")
prompt_add = st.text_area("② 追加指示 (描きたいもの):", value="", placeholder="例: 日本の街並みを歩く柴犬")
negative_ja = st.text_area("NGプロンプト (除外したいもの):", value="", placeholder="例: 文字、低画質、変な手")

# 3. 翻訳と合体
combined_en = ""
negative_en = ""

if prompt_base or prompt_add:
    # スペースで区切って合体させてから翻訳
    full_prompt_ja = f"{prompt_base} {prompt_add}"
    combined_en = GoogleTranslator(source='ja', target='en').translate(full_prompt_ja)
    
    if negative_ja:
        negative_en = GoogleTranslator(source='ja', target='en').translate(negative_ja)

# 4. 生成ボタン
if st.button("✨ 画像を生成する"):
    if not (prompt_base or prompt_add):
        st.warning("何か指示を入力してください")
    else:
        with st.spinner("SD3.5 Largeが画像を生成中です..."):
            # サーバーに送るデータ
            payload = {
                "inputs": combined_en,
                "parameters": {
                    "negative_prompt": negative_en
                }
            }
            
            # リクエスト送信
            response = requests.post(API_URL, headers=headers, json=payload)
            
            if response.status_code == 200:
                # 成功
                image = Image.open(io.BytesIO(response.content))
                st.image(image, caption="Generated by SD3.5 Large", use_container_width=True)
            elif response.status_code == 503:
                # 起動待ち
                st.info("モデルが準備中です。1分ほど待ってからもう一度試してください。")
            elif response.status_code == 403:
                st.error("アクセス権限エラー。Hugging Faceでの承認が反映されていない可能性があります。")
            else:
                # その他エラー
                st.error(f"エラーが発生しました (Status: {response.status_code})")
                st.write("詳細:", response.text)
